version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: website
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: C^t69TwRz*E0W98
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mariadb
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: C^t69TwRz*E0W98
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:
